/* confdefs.h */
#define PACKAGE_NAME "univalue"
#define PACKAGE_TARNAME "univalue"
#define PACKAGE_VERSION "1.0.3"
#define PACKAGE_STRING "univalue 1.0.3"
#define PACKAGE_BUGREPORT "http://github.com/jgarzik/univalue/"
#define PACKAGE_URL ""
#define PACKAGE "univalue"
#define VERSION "1.0.3"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
